const world_1 = {
    cw:24,ch:18,
    player:{cx:2,cy:3},
    tiles:[
        {cx:0 ,cy:0 ,id:'SMAS-SMB1-grass-0'},
        {cx:1 ,cy:0 ,id:'SMAS-SMB1-grass-1'},
        {cx:2 ,cy:0 ,id:'SMAS-SMB1-grass-1'},
        {cx:3 ,cy:0 ,id:'SMAS-SMB1-grass-1'},
        {cx:4 ,cy:0 ,id:'SMAS-SMB1-grass-1'},
        {cx:5 ,cy:0 ,id:'SMAS-SMB1-grass-1'},
        {cx:6 ,cy:0 ,id:'SMAS-SMB1-grass-1'},
        {cx:7 ,cy:0 ,id:'SMAS-SMB1-grass-2'},
        {cx:0 ,cy:1 ,id:'SMAS-SMB1-grass-3'},
        {cx:1 ,cy:1 ,id:'SMAS-SMB1-grass-4'},
        {cx:2 ,cy:1 ,id:'SMAS-SMB1-grass-4'},
        {cx:3 ,cy:1 ,id:'SMAS-SMB1-grass-4'},
        {cx:4 ,cy:1 ,id:'SMAS-SMB1-grass-4'},
        {cx:5 ,cy:1 ,id:'SMAS-SMB1-grass-4'},
        {cx:6 ,cy:1 ,id:'SMAS-SMB1-grass-4'},
        {cx:7 ,cy:1 ,id:'SMAS-SMB1-grass-5'},
        {cx:0 ,cy:2 ,id:'SMAS-SMB1-grass-3'},
        {cx:1 ,cy:2 ,id:'SMAS-SMB1-grass-4'},
        {cx:2 ,cy:2 ,id:'SMAS-SMB1-grass-4'},
        {cx:3 ,cy:2 ,id:'SMAS-SMB1-grass-4'},
        {cx:4 ,cy:2 ,id:'SMAS-SMB1-grass-4'},
        {cx:5 ,cy:2 ,id:'SMAS-SMB1-grass-4'},
        {cx:6 ,cy:2 ,id:'SMAS-SMB1-grass-4'},
        {cx:7 ,cy:2 ,id:'SMAS-SMB1-grass-5'},
        {cx:0 ,cy:3 ,id:'SMAS-SMB1-grass-3'},
        {cx:1 ,cy:3 ,id:'SMAS-SMB1-grass-4'},
        {cx:2 ,cy:3 ,id:'SMAS-SMB1-grass-4'},
        {cx:3 ,cy:3 ,id:'SMAS-SMB1-grass-4'},
        {cx:4 ,cy:3 ,id:'SMAS-SMB1-grass-4'},
        {cx:5 ,cy:3 ,id:'SMAS-SMB1-grass-4'},
        {cx:6 ,cy:3 ,id:'SMAS-SMB1-grass-4'},
        {cx:7 ,cy:3 ,id:'SMAS-SMB1-grass-5'},
        {cx:0 ,cy:4 ,id:'SMAS-SMB1-grass-6'},
        {cx:1 ,cy:4 ,id:'SMAS-SMB1-grass-7'},
        {cx:2 ,cy:4 ,id:'SMAS-SMB1-grass-7'},
        {cx:3 ,cy:4 ,id:'SMAS-SMB1-grass-7'},
        {cx:4 ,cy:4 ,id:'SMAS-SMB1-grass-7'},
        {cx:5 ,cy:4 ,id:'SMAS-SMB1-grass-7'},
        {cx:6 ,cy:4 ,id:'SMAS-SMB1-grass-7'},
        {cx:7 ,cy:4 ,id:'SMAS-SMB1-grass-8'},
    ],
    paths:[
        {cx:2 ,cy:3 ,id:'SMAS-SMB1-path1-14'},
        {cx:2 ,cy:2 ,id:'SMAS-SMB1-path1-1'},
        {cx:2 ,cy:1 ,id:'SMAS-SMB1-path1-2'},
        {cx:3 ,cy:1 ,id:'SMAS-SMB1-path1-0'},
        {cx:4 ,cy:1 ,id:'SMAS-SMB1-path1-0'},
        {cx:5 ,cy:1 ,id:'SMAS-SMB1-path-level-1'},
    ],
}

const level_1 = {
    cw:35,ch:25,
    player:{cx:3,cy:5},
    blocks:[
        {cx:3 ,cy:2 ,id:'SMAS-SMB1-block1-0'},
        {cx:4 ,cy:2 ,id:'SMAS-SMB1-block1-0'},
        {cx:5 ,cy:2 ,id:'SMAS-SMB1-block1-0'},
        {cx:6 ,cy:2 ,id:'SMAS-SMB1-block1-0'},
        {cx:7 ,cy:2 ,id:'SMAS-SMB1-block1-0'},
        {cx:5 ,cy:5 ,id:'SMAS-SMB1-bridge1-0'},
        {cx:6 ,cy:5 ,id:'SMAS-SMB1-bridge1-0'},
        {cx:7 ,cy:5 ,id:'SMAS-SMB1-bridge1-0'},
        {cx:18,cy:3 ,id:'SMAS-SMB1-block1-0'},
        {cx:19,cy:3 ,id:'SMAS-SMB1-block1-0'},
        {cx:20,cy:3 ,id:'SMAS-SMB1-block1-0'},
        {cx:21,cy:3 ,id:'SMAS-SMB1-block1-0'},
        {cx:22,cy:3 ,id:'SMAS-SMB1-block1-0'},
        {cx:21,cy:7 ,id:'SMAS-SMB1-block1-0'},
        {cx:22,cy:7 ,id:'SMAS-SMB1-block1-0'},
        {cx:23,cy:7 ,id:'SMAS-SMB1-block1-0'},
        {cx:24,cy:7 ,id:'SMAS-SMB1-block1-0'},
        {cx:25,cy:7 ,id:'SMAS-SMB1-block1-0'},
    ]
}